CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,

    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    password TEXT DEFAULT NULL,    

    -- Timestamps, with no time zone (TIMESTAMP)
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
