@baseUrl = http://localhost:8080
@contentType = application/json


# @name signIn
POST {{baseUrl}}/sign-in HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "user1@email.com",
    "password": "1234"
}

###

@authToken = {{signIn.response.body.data.authUser.refreshToken}}

###

# @name updateUser
PATCH {{baseUrl}}/users HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "name": "User 01",
    "userId": "01997da4-dc00-76e7-8a91-04c01c7d9a39"
}

###


# @name getUserById
GET {{baseUrl}}/users/01997da4-dc00-76e7-8a91-04c01c7d9a39 HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

###


# @name getUsers
GET {{baseUrl}}/users HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

###